name: Assign Issue to Project on Label

on:
  issues:
    types: [labeled]

jobs:
  assign_issue_to_project:
    if: contains(github.event.label.name, 'team:design')
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to project
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const projectNumber = 3;  // Your project number
            const username = 'Bodeman';  // Your GitHub username
            const issueNodeId = context.payload.issue.node_id;

            // Query to get the project ID
            const projectQuery = `
            query($username: String!, $projectNumber: Int!) {
              user(login: $username) {
                projectV2(number: $projectNumber) {
                  id
                }
              }
            }`;

            const projectResult = await github.graphql(projectQuery, {
              username: username,
              projectNumber: projectNumber
            });

            const projectId = projectResult.user.projectV2.id;

            // Mutation to add the issue to the project
            const addToProjectMutation = `
            mutation($projectId: ID!, $contentId: ID!) {
              addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                item {
                  id
                }
              }
            }`;

            await github.graphql(addToProjectMutation, {
              projectId: projectId,
              contentId: issueNodeId
            });