name: Assign Issue to Project

on:
  issues:
    types: [labeled]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PROJECT_NUMBER: 3  # Replace with your project number

jobs:
  assign-to-project:
    runs-on: ubuntu-latest
    steps:
    - name: Assign issue to project
      if: github.event.label.name == 'team:design'  # Replace with your label name
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        ORGANIZATION: ${{ github.repository_owner }}
        REPOSITORY: ${{ github.repository }}
      run: |
        echo "Assigning issue to project..."
        
        # Get project ID
        project_id=$(gh api graphql -f query='
          query($org: String!, $number: Int!) {
            organization(login: $org){
              projectV2(number: $number) {
                id
              }
            }
          }' -f org=$ORGANIZATION -f number=$PROJECT_NUMBER --jq '.data.organization.projectV2.id')
        
        echo "Project ID: $project_id"
        
        # Get issue node ID
        issue_node_id=$(gh api graphql -f query='
          query($org: String!, $repo: String!, $number: Int!) {
            repository(owner: $org, name: $repo) {
              issue(number: $number) {
                id
              }
            }
          }' -f org=$ORGANIZATION -f repo=$REPOSITORY -f number=$ISSUE_NUMBER --jq '.data.repository.issue.id')
        
        echo "Issue Node ID: $issue_node_id"
        
        # Add issue to project
        gh api graphql -f query='
          mutation($project:ID!, $issue:ID!) {
            addProjectV2ItemById(input: {projectId: $project, contentId: $issue}) {
              item {
                id
              }
            }
          }' -f project=$project_id -f issue=$issue_node_id
        
        echo "Issue assigned to project successfully"