name: Assign Issue to Project on Label

on:
  issues:
    types: [labeled]

jobs:
  assign_issue_to_project:
    if: contains(github.event.label.name, 'team:design')
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to project
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = context.issue.number;
            const projectId = '3';  // Add your project ID here
            const contentId = context.payload.issue.node_id;

            // GraphQL mutation to add the issue to the project
            const mutation = `
            mutation ($projectId: ID!, $contentId: ID!) {
              addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                item {
                  id
                }
              }
            }`;

            await github.graphql(mutation, {
              projectId: projectId,
              contentId: contentId
            });