name: Assign to Project

on:
  issues:
    types: [opened]

jobs:
  assign_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/Bodeman/projects/3/views/1
          github-token: ${{ secrets.GITHUB_TOKEN }}